# Generated by Django 5.1.3 on 2024-12-31 19:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import segmentations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinic", "0001_initial"),
        ("phases", "0001_initial"),
        ("quality", "0001_initial"),
        ("views", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SegmentationClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "icid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("value", models.CharField(max_length=32, unique=True)),
                (
                    "view_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="segmentation_classes",
                        to="views.viewclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmentation Class",
                "verbose_name_plural": "Segmentation Classes",
            },
        ),
        migrations.CreateModel(
            name="SegmentationLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "icid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=segmentations.models.SegmentationLabel.upload_to,
                    ),
                ),
                ("extension", models.CharField(blank=True, max_length=3, null=True)),
                ("paths", models.JSONField(blank=True, null=True)),
                ("is_fully_visible", models.BooleanField(default=True)),
                ("accepted", models.BooleanField(blank=True, null=True)),
                (
                    "deny_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BAD_DICOM", "Bad DICOM"),
                            ("BAD_LABEL", "Bad Label"),
                        ],
                        default=None,
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "cardiac_cycle_phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation_labels",
                        to="phases.phaseclass",
                    ),
                ),
                (
                    "frame",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation_labels",
                        to="clinic.frame",
                    ),
                ),
                (
                    "quality_label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segmentation_labels",
                        to="quality.qualitylabel",
                    ),
                ),
                (
                    "review_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segmentation_label_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "segmentation_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="segmentation_labels",
                        to="segmentations.segmentationclass",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmentation Label",
                "verbose_name_plural": "Segmentation Labels",
                "unique_together": {("user", "frame", "segmentation_class")},
            },
        ),
    ]
