# Generated by Django 5.1.3 on 2024-12-31 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_media_options'),
        ('phases', '0002_alter_phaseclass_options_alter_phaselabel_options'),
        ('segmentations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segmentationlabel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='segmentationlabel',
            constraint=models.UniqueConstraint(fields=('user', 'frame', 'segmentation_class'), name='unique_user_frame_segmentation_class'),
        ),
        migrations.RemoveField(
            model_name='segmentationlabel',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='segmentationlabel',
            name='deny_reason',
        ),
        migrations.RemoveField(
            model_name='segmentationlabel',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='segmentationlabel',
            name='quality_label',
        ),
        migrations.RemoveField(
            model_name='segmentationlabel',
            name='review_user',
        ),
    ]
