# Generated by Django 5.1.3 on 2024-12-31 19:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dicom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "icid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="upload_to"),
                ),
                ("index", models.IntegerField(blank=True, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "manufacturer_model_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "physical_units_x_direction",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "physical_units_y_direction",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("physical_delta_x", models.FloatField(blank=True, null=True)),
                ("physical_delta_y", models.FloatField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Color", "Color"),
                            ("Standard", "Standard"),
                            ("Single Frame", "Single Frame"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("number_of_frames", models.IntegerField(blank=True, null=True)),
                ("pixel_height", models.IntegerField(blank=True, null=True)),
                ("pixel_width", models.IntegerField(blank=True, null=True)),
                ("frames_per_second", models.FloatField(blank=True, null=True)),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRAIN", "Train"),
                            ("TEST", "Test"),
                            ("VAL", "Validation"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "icid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="upload_to"),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True,
                        choices=[("mp4", "mp4"), ("png", "png")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "dicom",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="clinic.dicom",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Media",
            },
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "icid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("index", models.IntegerField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="upload_to"),
                ),
                ("extension", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="clinic.media",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "icid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("number_of_dicoms", models.IntegerField(blank=True, null=True)),
                ("number_of_usable_dicoms", models.IntegerField(blank=True, null=True)),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRAIN", "Train"),
                            ("TEST", "Test"),
                            ("VAL", "Validation"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Studies",
                "indexes": [
                    models.Index(
                        fields=["designation"], name="clinic_stud_designa_d07667_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="dicom",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dicoms",
                to="clinic.study",
            ),
        ),
        migrations.AddIndex(
            model_name="dicom",
            index=models.Index(
                fields=["designation"], name="clinic_dico_designa_bbc8c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dicom",
            index=models.Index(fields=["type"], name="clinic_dico_type_527d23_idx"),
        ),
        migrations.AddConstraint(
            model_name="dicom",
            constraint=models.UniqueConstraint(
                fields=("study", "index"), name="unique_study_index"
            ),
        ),
    ]
