# Generated by Django 5.1.3 on 2024-12-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={},
        ),
    ]
