# Generated by Django 5.1.3 on 2024-12-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phaseclass',
            options={'verbose_name': 'Phase Class', 'verbose_name_plural': 'Phase Classes'},
        ),
        migrations.AlterModelOptions(
            name='phaselabel',
            options={'verbose_name': 'Phase Label', 'verbose_name_plural': 'Phase Labels'},
        ),
    ]
