# Generated by Django 5.1.3 on 2024-12-31 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('clinic', '0001_initial'),
        ('segmentations', '0001_initial'),
        ('views', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomlabelingjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_labeling_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fullstudyannotationset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_study_annotation_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dicomlabelingjob',
            name='annotation_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_labeling_jobs', to='assignments.fullstudyannotationset'),
        ),
        migrations.AddField(
            model_name='segmentationlabelingjob',
            name='annotation_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmentation_labeling_jobs', to='assignments.fullstudyannotationset'),
        ),
        migrations.AddField(
            model_name='segmentationlabelingjob',
            name='diastolic_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diastolic_segmentation_labeling_jobs', to='segmentations.segmentationlabel'),
        ),
        migrations.AddField(
            model_name='segmentationlabelingjob',
            name='dicom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_labeling_jobs', to='clinic.dicom'),
        ),
        migrations.AddField(
            model_name='segmentationlabelingjob',
            name='segmentation_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_labeling_jobs', to='segmentations.segmentationclass'),
        ),
        migrations.AddField(
            model_name='segmentationlabelingjob',
            name='systolic_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systolic_segmentation_labeling_jobs', to='segmentations.segmentationlabel'),
        ),
        migrations.AddField(
            model_name='segmentationlabelingjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_labeling_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='segmentationlabelingjob',
            name='view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_labeling_jobs', to='views.viewclass'),
        ),
        migrations.AddField(
            model_name='studylabelingjob',
            name='annotation_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_labeling_jobs', to='assignments.fullstudyannotationset'),
        ),
        migrations.AddField(
            model_name='studylabelingjob',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_labeling_jobs', to='clinic.study'),
        ),
        migrations.AddField(
            model_name='studylabelingjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_labeling_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dicomlabelingjob',
            name='study_labeling_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_labeling_jobs', to='assignments.studylabelingjob'),
        ),
        migrations.AddConstraint(
            model_name='segmentationlabelingjob',
            constraint=models.UniqueConstraint(fields=('dicom', 'user', 'segmentation_class', 'annotation_set'), name='unique_segmentation_labeling_job'),
        ),
        migrations.AddConstraint(
            model_name='studylabelingjob',
            constraint=models.UniqueConstraint(fields=('study', 'user', 'annotation_set'), name='unique_study_labeling_job'),
        ),
    ]
