# Generated by Django 5.1.3 on 2024-12-31 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SegmentationLabelingJob',
        ),
    ]
