# Generated by Django 5.1.3 on 2024-12-31 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('icid', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quality_class', models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad')], max_length=10, null=True)),
                ('dicom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_labels', to='clinic.dicom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quality Label',
                'verbose_name_plural': 'Quality Labels',
                'unique_together': {('user', 'dicom')},
            },
        ),
    ]
