# Generated by Django 5.1.3 on 2024-12-31 19:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "icid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("window", models.CharField(blank=True, max_length=40, null=True)),
                ("view", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("Standard", "Standard"), ("Color", "Color")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        blank=True,
                        choices=[("Video", "Video"), ("Single Frame", "Single Frame")],
                        default="Video",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ("media_type", "type", "window", "view"),
                "unique_together": {("window", "view", "type", "media_type")},
            },
        ),
        migrations.CreateModel(
            name="ViewLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "icid",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("denied", models.BooleanField(null=True)),
                (
                    "dicom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_labels",
                        to="clinic.dicom",
                    ),
                ),
                (
                    "review_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="view_label_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_labels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "view_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="view_labels",
                        to="views.viewclass",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "dicom")},
            },
        ),
    ]
