# Generated by Django 5.1.3 on 2024-12-31 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_media_options'),
        ('views', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewclass',
            options={'verbose_name': 'View Class', 'verbose_name_plural': 'View Classes'},
        ),
        migrations.AlterModelOptions(
            name='viewlabel',
            options={'verbose_name': 'View Label', 'verbose_name_plural': 'View Labels'},
        ),
        migrations.AlterUniqueTogether(
            name='viewclass',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='viewlabel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='viewclass',
            constraint=models.UniqueConstraint(fields=('window', 'view', 'type', 'media_type'), name='unique_view_class'),
        ),
        migrations.AddConstraint(
            model_name='viewlabel',
            constraint=models.UniqueConstraint(fields=('user', 'dicom'), name='unique_view_per_user_dicom'),
        ),
        migrations.RemoveField(
            model_name='viewlabel',
            name='denied',
        ),
        migrations.RemoveField(
            model_name='viewlabel',
            name='review_user',
        ),
    ]
